source("ini_value.R")
xxx <- seq(0,8,length.out=10000)
setEPS()
postscript(file="Fig1(1).eps")
par(mfrow=c(1,3))
#1,1
plot(x=xxx,y=dweibull(xxx,shape_weib,scale_weib),xlab="Time",ylab="Density",lty=1,ylim=c(0,0.6),type="l")
lines(x=xxx,y=labda*exp(gama*xxx)*exp(-labda/gama*(exp(gama*xxx)-1)),lty=2)
lines(x=xxx,y=dlnorm(xxx,meanlog,sdlog),lty=3)
lines(x=xxx,y=dunif(xxx,min_unif,max_unif),lty=4)
legend("topright",legend=c("Weibull","Gompertz","lognormal","uniform"),lty=1:4)
#1,2
plot(x=xxx,y=pweibull(xxx,shape_weib,scale_weib,lower.tail = F),xlab="Time",ylab="Survival",lty=1,ylim=c(0,1),type="l")
lines(x=xxx,y=exp(-labda/gama*(exp(gama*xxx)-1)),lty=2)
lines(x=xxx,y=plnorm(xxx,meanlog,sdlog,lower.tail = F),lty=3)
lines(x=xxx,y=punif(xxx,min_unif,max_unif,lower.tail = F),lty=4)
legend("topright",legend=c("Weibull","Gompertz","lognormal","uniform"),lty=1:4)
#1,3
plot(x=xxx,y=dweibull(xxx,shape_weib,scale_weib)/pweibull(xxx,shape_weib,scale_weib,lower.tail = F),xlab="Time",ylab="Density",lty=1,ylim=c(0,1),type="l")
lines(x=xxx,y=labda*exp(gama*xxx),lty=2)
lines(x=xxx,y=dlnorm(xxx,meanlog,sdlog)/plnorm(xxx,meanlog,sdlog,lower.tail = F),lty=3)
lines(x=xxx,y=dunif(xxx,min_unif,max_unif)/punif(xxx,min_unif,max_unif,lower.tail = F),lty=4)
legend("topright",legend=c("Weibull","Gompertz","lognormal","uniform"),lty=1:4)

dev.off()